# Imagen base de python
FROM python:3.12.5-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar la lista de dependencias
COPY requirements.txt requirements.txt

# Instalar dependencias
RUN pip install -r requirements.txt

# Copiar el resto de los archivos
COPY . .

# Exponer el puerto 8000
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["fastapi", "dev", "main.py"]