name: Dev CI - GitHub CR Build & Push

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    NAME: dev/opendata
    NAMESPACE: unicaribe-dev
    ORG: ghcr.io
    TAG: latest

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v4

            - name: Iniciar sesión en el registro de contenedores de GitHub
              run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u $NAMESPACE --password-stdin

            - name: Contruir imagen de Docker para el desarrollo
              run: docker build -t $ORG/$NAMESPACE/$NAME:$TAG -f Dockerfile.dev .

            - name: Subir imagen de Docker
              run: docker push $ORG/$NAMESPACE/$NAME:$TAG